### ISSUE TITLE
Refine model build filter

### ISSUE THREAD

**Issue by jialeicui** [star-whale/starwhale#1798]
![image](https://user-images.githubusercontent.com/3217223/217228771-d9caa3a7-6068-4604-bde2-dd4f7b86cf04.png)

```yaml
version: 1.0
name: pfp
model:
  - models/mcrnn.pth
run:
  handler: pfp.evaluator:MaskRCnn
  pkg_data:
    - FudanPed00001.png
desc: mask rcnn resnet50 by pytorch
```
